import React from "react";
import styled from "@emotion/styled";
import { NameCardData } from "./data";
/**
 * `<Nc1A>` ('NC1A')
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <Nc1A/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](grida://assets-reservation/images/1:2709)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://undefined/1:2709 -->
 */
export function NC1A({ data }: { data: NameCardData }) {
  return (
    <RootWrapperNc1A>
      <DataCompany>{data.company}</DataCompany>
      <A>A.</A>
      <DataAddress>{data.address}</DataAddress>
      <E>E.</E>
      <DataEmail>{data.email}</DataEmail>
      <T>T.</T>
      <DataHandle>{data.handle}</DataHandle>
      <P>P.</P>
      <DataTelephone>{data.tel}</DataTelephone>
      <DataCompanyDescription>
        {data.company_description}
      </DataCompanyDescription>
    </RootWrapperNc1A>
  );
}

const RootWrapperNc1A = styled.div`
  width: 900px;
  height: 500px;
  background-color: white;
`;

const DataCompany = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: "Source Code Pro", sans-serif;
  font-weight: 500;
  text-align: left;
  position: absolute;
  left: 60px;
  top: 47px;
`;

const A = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: "Source Code Pro", sans-serif;
  font-weight: 500;
  text-align: left;
  position: absolute;
  left: 60px;
  top: 301px;
`;

const DataAddress = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: "Source Code Pro", sans-serif;
  font-weight: 500;
  text-align: left;
  position: absolute;
  left: 389px;
  top: 301px;
`;

const E = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: "Source Code Pro", sans-serif;
  font-weight: 500;
  text-align: left;
  position: absolute;
  left: 60px;
  top: 342px;
`;

const DataEmail = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: "Source Code Pro", sans-serif;
  font-weight: 500;
  text-align: left;
  position: absolute;
  left: 389px;
  top: 342px;
`;

const T = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: "Source Code Pro", sans-serif;
  font-weight: 500;
  text-align: left;
  position: absolute;
  left: 60px;
  top: 383px;
`;

const DataHandle = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: "Source Code Pro", sans-serif;
  font-weight: 500;
  text-align: left;
  position: absolute;
  left: 389px;
  top: 383px;
`;

const P = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: "Source Code Pro", sans-serif;
  font-weight: 500;
  text-align: left;
  position: absolute;
  left: 60px;
  top: 424px;
`;

const DataTelephone = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: "Source Code Pro", sans-serif;
  font-weight: 500;
  text-align: left;
  position: absolute;
  left: 389px;
  top: 424px;
`;

const DataCompanyDescription = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: "Source Code Pro", sans-serif;
  font-weight: 500;
  text-align: left;
  width: 239px;
  position: absolute;
  left: 389px;
  top: 47px;
`;
